### ISSUE TITLE
Is this supposed to work on ST3/Mac?

### ISSUE THREAD

**Issue by alindsay55661** [mazurov/sublime-levels#4]
Installation went fine but I can't seem to get any highlighting to show up. Theme issue?

**Comment by mazurov** [comment]
I don't have Mac for tests, but it supposed to work on Mac. Did you check ST console messages/warnings/errors?

**Comment by alindsay55661** [comment]
Checked console, no messages, warnings or errors. It is behaving as if the plugin is not installed. It does show up under `Package Control -> List Packages`, however.

**Comment by mazurov** [comment]
How did you install it? Did you use Package Control and insert repository url like it was described in README? Did the package appears in ST Packages directory? Package does not have any special checks for OS, so first you need to be sure that you installed it :smile:

**Comment by alindsay55661** [comment]
I installed via Package Control by adding the repo as suggested. Sublime Package Control reports that the package is installed. Additionally, the package folder (and contents) are located in the Sublime Packages directory on the file system. Other than actually highlighting code, this package appears to be installed. But I did notice that it doesn't have its own settings menu, I need to go to the file system to edit settings.

**Comment by mazurov** [comment]
Select your javascript file and check:
(1) If your file has Javascript syntax: Try execute command: "Set syntax: JavaScript" (the plugin is enabled only if the syntax mode has "JavaScript" in its name).
(2) Is the command "Levels: Update" exists in the ST Command palette (In case if keyboard shortcuts does not work).

I can confirm that there are no settings in "Package Settings:" menu for this package (will be in the next version this week),

**Comment by alindsay55661** [comment]
Ok, yes, the file is interpreted as JavaScript and no, there are no commands with the word "levels" available in ST Command palette.

**Comment by mazurov** [comment]
Strange that you don't see any warnings in ST console.

Next checks:
(1) In the package directory: If you copy "Default.sublime-commands" to "Default (OSX).sublime-commands" does the command "Levels: Update" appears (first you need select any javascript file)
(2) Do you have Packages/PyV8 folder in ST packages? Does it contains any files?
(3) If you run "import sys; print(sys.path)" does "subilme-levels" appears in the list?

**Comment by alindsay55661** [comment]
> (1) In the package directory: If you copy "Default.sublime-commands" to "Default (OSX).sublime-commands" does the command "Levels: Update" appears (first you need select any javascript file)

Unfortunately, no.

> (2) Do you have Packages/PyV8 folder in ST packages? Does it contains any files?

Also, no.

> (3) If you run "import sys; print(sys.path)" does "subilme-levels" appears in the list?

Yes!

**Comment by mazurov** [comment]
It can be  the problems with automatic installation of PyV8 package (it was mentioned in readme file. do you see any messages realated to PyV8 in SublimeText console?). 

Please try to download https://github.com/emmetio/pyv8-binaries/raw/master/pyv8-osx.zip and unpack it to Packages/PyV8 folder. Restart ST and try the plugin again.

**Comment by alindsay55661** [comment]
Wow, yes, I am getting all kinds of errors now. Looks like lots of stuff is failing. Did I miss this before?

```
reloading plugin PyV8.PyV8
Traceback (most recent call last):
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/PyV8/PyV8.py", line 23, in <module>
    from cStringIO import StringIO
ImportError: No module named 'cStringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 72, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/PyV8/PyV8.py", line 25, in <module>
    from StringIO import StringIO
ImportError: No module named 'StringIO'

reloading plugin sublime-levels.levels_plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 72, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/sublime-levels/levels_plugin.py", line 34, in <module>
    import levels.pyv8loader as pyv8loader
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/sublime-levels/levels/pyv8loader.py", line 12, in <module>
    import semver
ImportError: No module named 'semver'
```

There are other packages failing as well.

**Comment by mazurov** [comment]
My fault: you need PyV8 for python3: https://github.com/emmetio/pyv8-binaries/raw/master/pyv8-osx-p3.zip. 

You can try to install it, but I see that the bug in  loading semver module (if it will be fixed the PyV8 module will be downloaded automatically). So I will return to the issue tomorrow - it's a midnight in Europe =)

**Comment by alindsay55661** [comment]
Sure thing, thanks for the help. Getting new errors on this version of PyV8 as well:

```
reloading plugin PyV8.PyV8
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 72, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/PyV8/PyV8.py", line 32, in <module>
    import _PyV8
ImportError: No module named '_PyV8'
```

**Comment by mazurov** [comment]
I found that currently the plugin could not be installed from Package Control in ST3 (In ST2 should work). Use manual installation as described in README (clone or download and extract to Packages). Remove PyV8 folder from Packages folder - PyV8 will be installed automatically. I will fix it soon.

**Comment by i-akhmadullin** [comment]
I can confirm that sublime-levels works perfectly fine in ST3 on Mac. And i was able to reinstall plugin with Package Control(2.0.0-alpha2) without any problems. I think problem is that maybe you using stable Package Control which doesn't reliably works on ST2.

**Comment by mazurov** [comment]
@i-akhmadullin  Do you have unpacked version in Packages folder  or sublime-package archive in "Installed Packages"? I found problems with archived version of the package. I installed Package Control from git: git clone ... ; git checkout python3.

**Comment by mazurov** [comment]
Current Package Control version from git does not unpack sublime-package archive to Packages folder. And the plugin does not want to work from archive.

**Comment by i-akhmadullin** [comment]
I installed plugin with package control ("Add Repository"-> "Install...") and Package Control created sublime-levels folder in Packages folder by itself. Got some errors in console (but .sublime-package file still was extracted correctly):

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 615, in update_compressed_packages
    multi_importer.loaders = [ZipLoader(p) for p in pkgs]
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 615, in <listcomp>
    multi_importer.loaders = [ZipLoader(p) for p in pkgs]
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 565, in __init__
    z = zipfile.ZipFile(path, 'r')
  File "X/zipfile.py", line 897, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ilia/Library/Application Support/Sublime Text 3/Installed Packages/sublime-levels.sublime-package'
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
```

**Comment by mazurov** [comment]
**Edited**: @i-akhmadullin the warnings in your message is OK. But if you will install a fresh version of Package Control from git and python3 branch you will see  another errors.

But :smile: ! I [found](https://github.com/wbond/sublime_package_control/issues/349) that it's possible tell to Package Control to extract files. Have just pushed the changes and now you can do "Package Control: Upgrade Package" for sublime-levels and it should work. Check, please

**Comment by mazurov** [comment]
@alindsay55661 could you try to remove the package  from Package Control list and try to install the fresh version of the plugin? By the way what Package Control version do you use? You can see this version with "Package Control: List Packages" command.

**Comment by i-akhmadullin** [comment]
Just tried to install plugin with latest version of package control. Installation went perfectly as before but this time didn't get any exceptions :)

**Comment by alindsay55661** [comment]
Sorry for the delay, was traveling. I updated to the latest version of package control (v2.0alpha6) and am getting this error when trying to install sublime-levels:

```
reloading plugin sublime-levels.levels_plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/sublime-levels/levels_plugin.py", line 34, in <module>
    import levels.pyv8loader as pyv8loader
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/sublime-levels/levels/pyv8loader.py", line 12, in <module>
    import semver
ImportError: No module named 'semver'
```

**Comment by alindsay55661** [comment]
I tried to update manually (installed via `git clone`) and I get this error:

```
reloading plugin Levels.levels_plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/Levels/levels_plugin.py", line 34, in <module>
    import levels.pyv8loader as pyv8loader
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/sublime-levels/levels/pyv8loader.py", line 12, in <module>
    import semver
ImportError: No module named 'semver'
ignored packages updated to: [Vintage, sublime-levels]
```

**Comment by alindsay55661** [comment]
I attempted to use the zip-file method and get the following error:

```
reloading plugin sublime-levels.levels_plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/sublime-levels/levels_plugin.py", line 34, in <module>
    import levels.pyv8loader as pyv8loader
  File "/Users/alindsay/Library/Application Support/Sublime Text 3/Packages/sublime-levels/levels/pyv8loader.py", line 12, in <module>
    import semver
ImportError: No module named 'semver'
```

**Comment by mazurov** [comment]
@alindsay55661 Recently I have updated the plugin. Do you still have the problems with the plugin?
